<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<!-- This is the GNU Emacs Lisp Reference Manual
corresponding to Emacs version 24.5.

Copyright (C) 1990-1996, 1998-2015 Free Software Foundation, Inc.

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with the
Invariant Sections being "GNU General Public License," with the
Front-Cover Texts being "A GNU Manual," and with the Back-Cover
Texts as in (a) below.  A copy of the license is included in the
section entitled "GNU Free Documentation License."

(a) The FSF's Back-Cover Text is: "You have the freedom to copy and
modify this GNU manual.  Buying copies from the FSF supports it in
developing GNU and promoting software freedom." -->
<!-- Created by GNU Texinfo 6.5, http://www.gnu.org/software/texinfo/ -->
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Examples of Catch (GNU Emacs Lisp Reference Manual)</title>

<meta name="description" content="Examples of Catch (GNU Emacs Lisp Reference Manual)">
<meta name="keywords" content="Examples of Catch (GNU Emacs Lisp Reference Manual)">
<meta name="resource-type" content="document">
<meta name="distribution" content="global">
<meta name="Generator" content="makeinfo">
<link href="index.html#Top" rel="start" title="Top">
<link href="Index.html#Index" rel="index" title="Index">
<link href="index.html#SEC_Contents" rel="contents" title="Table of Contents">
<link href="Nonlocal-Exits.html#Nonlocal-Exits" rel="up" title="Nonlocal Exits">
<link href="Errors.html#Errors" rel="next" title="Errors">
<link href="Catch-and-Throw.html#Catch-and-Throw" rel="prev" title="Catch and Throw">
<style type="text/css">
<!--
a.summary-letter {text-decoration: none}
blockquote.indentedblock {margin-right: 0em}
blockquote.smallindentedblock {margin-right: 0em; font-size: smaller}
blockquote.smallquotation {font-size: smaller}
div.display {margin-left: 3.2em}
div.example {margin-left: 3.2em}
div.lisp {margin-left: 3.2em}
div.smalldisplay {margin-left: 3.2em}
div.smallexample {margin-left: 3.2em}
div.smalllisp {margin-left: 3.2em}
kbd {font-style: oblique}
pre.display {font-family: inherit}
pre.format {font-family: inherit}
pre.menu-comment {font-family: serif}
pre.menu-preformatted {font-family: serif}
pre.smalldisplay {font-family: inherit; font-size: smaller}
pre.smallexample {font-size: smaller}
pre.smallformat {font-family: inherit; font-size: smaller}
pre.smalllisp {font-size: smaller}
span.nolinebreak {white-space: nowrap}
span.roman {font-family: initial; font-weight: normal}
span.sansserif {font-family: sans-serif; font-weight: normal}
ul.no-bullet {list-style: none}
-->
</style>


</head>

<body lang="en">
<a name="Examples-of-Catch"></a>
<div class="header">
<p>
Next: <a href="Errors.html#Errors" accesskey="n" rel="next">Errors</a>, Previous: <a href="Catch-and-Throw.html#Catch-and-Throw" accesskey="p" rel="prev">Catch and Throw</a>, Up: <a href="Nonlocal-Exits.html#Nonlocal-Exits" accesskey="u" rel="up">Nonlocal Exits</a> &nbsp; [<a href="index.html#SEC_Contents" title="Table of contents" rel="contents">Contents</a>][<a href="Index.html#Index" title="Index" rel="index">Index</a>]</p>
</div>
<hr>
<a name="Examples-of-catch-and-throw"></a>
<h4 class="subsection">10.5.2 Examples of <code>catch</code> and <code>throw</code></h4>

<p>2重にネストされたループから脱出する1つの方法は、<code>catch</code>と<code>throw</code>を使うことです(ほとんどの言語では、これは&ldquo;goto&rdquo;により行なわれるでしょう)。ここでは、<var>i</var>と<var>j</var>を、0から9に変化させて<code>(foo
<var>i</var> <var>j</var>)</code>を計算します:
</p>
<div class="example">
<pre class="example">(defun search-foo ()
  (catch 'loop
    (let ((i 0))
      (while (&lt; i 10)
        (let ((j 0))
          (while (&lt; j 10)
            (if (foo i j)
                (throw 'loop (list i j)))
            (setq j (1+ j))))
        (setq i (1+ i))))))
</pre></div>

<p><code>foo</code>が非<code>nil</code>をreturnした場合、即座に処理を止めて、<var>i</var>と<var>j</var>のリストをreturnしています。<code>foo</code>が常に<code>nil</code>をreturnする場合、<code>catch</code>は通常どおりreturnし、その値は<code>while</code>の結果である<code>nil</code>となります。
</p>
<p>以下では、2つのreturn位置を1度に表す、微妙に異なるトリッキーな例を2つ示します。最初に、同じタグ<code>hack</code>にたいする2つのreturn位置があります:
</p>
<div class="example">
<pre class="example">(defun catch2 (tag)
  (catch tag
    (throw 'hack 'yes)))
&rArr; catch2
</pre><pre class="example">

</pre><pre class="example">(catch 'hack
  (print (catch2 'hack))
  'no)
-| yes
&rArr; no
</pre></div>

<p>どちらのreturn位置も<code>throw</code>にマッチするタグをもつので、内側のもの、つまり<code>catch2</code>で確立されたものにgotoします。したがって<code>catch2</code>は通常どおり値<code>yes</code>をreturnするので、その値がプリントされます。最後に外側の<code>catch</code>の2番目のbody、つまり<code>'no</code>が評価されて、外側の<code>catch</code>からそれがreturnされます。
</p>
<p>ここで、<code>catch2</code>に与える引数を変更してみます:
</p>
<div class="example">
<pre class="example">(catch 'hack
  (print (catch2 'quux))
  'no)
&rArr; yes
</pre></div>

<p>この場合も2つのreturn位置がありますが、今回は外側だけがタグ<code>hack</code>をもち、内側のものは、かわりにタグ<code>quux</code>をもちます。したがって、<code>throw</code>により、外側の<code>catch</code>が値<code>yes</code>をreturnします。関数<code>print</code>が呼び出されることはなく、bodyのフォーム<code>'no</code>も決して評価されません。
</p>



</body>
</html>
